#!/usr/bin/env python3
"""Build a self-contained pack so somebody who is not a developer can write her answers.

The measurement that makes this necessary: the training data is generated by the same 7B model
it then trains, filtered to the half that obeys the rules. Its ceiling is that model's own best
work, and no amount of sampling gets above your own ceiling. Human-written answers are the only
thing that raises it.

The person who writes them should not have to install Python, clone a repository, or read a
config file. So the pack is three files in one folder, and one of them is a writing tool that
opens in any browser and needs no network:

    BRIEF.md         who she is, what the rules are, what a good answer looks like
    write.html       the tool: one prompt at a time, live checks, exports a file
    questions.csv    the same prompts as a spreadsheet, for anyone who prefers Excel

The live checks in write.html are the same rules the production guard enforces — an invented
price, a claimed link, denying being AI. Catching those while the sentence is being written is
far kinder than rejecting the batch later, and it teaches the rules by using them.

WHY THE PROMPTS ARE A MIX. Of 435 real viewer comments harvested through the API, only 29 carry
a question and none ask for advice — real comment sections are mostly reactions. A pack built
only from them would teach her to respond to compliments. So the real ones supply the voice of
an actual audience and the written seeds supply the situations that matter and rarely arrive on
demand: somebody weighing a decision, somebody having a bad day.

    python tools/llm_train/make_writing_pack.py sofia-vargas --count 150
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools" / "llm_train"))
sys.path.insert(0, str(REPO / "tools" / "livestream"))

SEEDS_FILE = REPO / "datasets" / "style" / "viewers-seeds.txt"

# The questions an audience actually asks an entertainment creator, grouped by the thing each
# one forces her to do. That grouping is the design: a writer is not producing a FAQ, they are
# producing examples of a register, and each group exercises a different measured weakness.
#
# They are written rather than harvested, and that is deliberate rather than lazy. Of 435 real
# comments only 29 carry a question at all — a comment section is mostly reactions, so the
# questions that reveal a personality have to be supplied. The real ones are mixed in beside
# them so the pack still carries an actual audience's voice.
ENTERTAINMENT = {
    # Forces a verdict. She was measured stating an opinion in 7% of replies against 27% for
    # real people, and there is nowhere to hide in a two-way choice.
    "pick one": [
        "coffee or tea?", "beach or mountains?", "text or call?",
        "sweet or savoury breakfast?", "night out or night in?",
        "salsa or reggaeton?", "cook at home or order in?",
        "morning person or night owl?", "window seat or aisle?",
        "cats or dogs, and no diplomatic answers",
        "would you rather never eat rice again or never eat bread again?",
        "would you rather be always ten minutes early or always five minutes late?",
        "pineapple on pizza — settle it",
        "the best meal you can cook, or the best meal somebody cooks for you?",
    ],
    # Forces a narrative. Measured at 3% of her replies against 15% for real talk, the largest
    # gap of any measure taken.
    "tell me a story": [
        "tell me something ridiculous that happened to you",
        "what is the most embarrassing thing you have done on camera?",
        "worst travel story, go",
        "tell me about a time you were completely wrong about something",
        "what is the pettiest argument you have ever won?",
        "story of the last time you laughed until you cried",
        "what happened the first time you tried to post online?",
        "tell me about a meal that went badly wrong",
        "what is the worst haircut you have ever had?",
        "have you ever gotten lost somewhere? what happened",
        "what is the strangest thing a stranger has said to you?",
        "tell me about something you bought that was a complete waste",
    ],
    # Forces a position with a reason behind it. Different from "pick one": here she has to
    # defend it, which is where a personality either exists or does not.
    "hot take": [
        "what is a food opinion that gets you in trouble?",
        "something everyone loves that you just do not get",
        "what is overrated?", "what is underrated?",
        "the worst advice you hear people give constantly",
        "what trend do you refuse to do?",
        "is expensive skincare worth it or is that a scam?",
        "what is the most annoying thing people do online?",
        "a hill you would die on",
        "what do people get wrong about where you are from?",
    ],
    # Everyday specifics. She was measured carrying a concrete detail in 43% of replies against
    # 55% for real talk, and this is the material that produces them.
    "her day": [
        "what did you actually do today?", "what did you eat today?",
        "what is in your bag right now?", "what is your morning like?",
        "what is the last thing you bought?", "how was filming today?",
        "what is on your phone screen right now?",
        "what did you have for dinner, be honest",
        "what is the last show you finished?",
        "what is something small that annoyed you this week?",
        "what is the last photo in your camera roll?",
        "what time did you actually wake up?",
    ],
    # Banter. She has to take a joke, give one back, and not turn earnest — the register a
    # stream lives or dies on.
    "playing with her": [
        "rate your own cooking out of ten, be honest",
        "I bet you cannot go a day without coffee",
        "you definitely lose arguments with your cousin, admit it",
        "prove you are actually good at this game",
        "on a scale of one to ten how competitive are you really?",
        "what would your abuela say about your flat?",
        "I do not believe you can dance, show us",
        "guess what I had for lunch",
        "your plant is dying and everyone can see it",
    ],
    # About her, the way an audience asks it: nosy, casual, and not a job interview.
    "about her": [
        "do you get lonely doing this?", "do you miss home?",
        "what did you want to be as a kid?",
        "what is something nobody knows about you?",
        "what do you do when you are in a bad mood?",
        "are you actually like this in real life?",
        "what is the best thing about where you live now?",
        "do you ever get nervous on camera?",
        "what is the one thing you would never post?",
    ],
}


def gather(kol_id: str, count: int, seed: int = 0) -> list[dict]:
    """Entertainment prompts, grouped by what each one forces her to do.

    This is a style exercise, not a knowledge base. The writer is not producing answers that
    have to be right; they are producing examples of a register, and every group here exists
    because a specific measure came back short — a verdict, a story, a concrete detail, a joke
    taken and given back.

    Real harvested questions are mixed in beside the written ones so the pack still carries an
    actual audience's voice. Reactions from the harvest are included too, in small numbers:
    they are most of a real comment section and she still has to answer one without sliding
    into thanking people for watching.
    """
    rng = random.Random(seed)
    out, seen = [], set()

    for kind, items in ENTERTAINMENT.items():
        for t in items:
            if t.lower() not in seen:
                seen.add(t.lower())
                out.append({"kind": kind, "prompt": t})

    real = []
    if SEEDS_FILE.is_file():
        real = [l.strip() for l in SEEDS_FILE.read_text(encoding="utf-8").splitlines()
                if l.strip()]
    asks = [t for t in real if "?" in t]
    reacts = [t for t in real if "?" not in t]
    rng.shuffle(asks)
    rng.shuffle(reacts)

    for t in asks:
        if t.lower() not in seen:
            seen.add(t.lower())
            out.append({"kind": "a real viewer asked", "prompt": t})
    # Capped at a tenth of the pack. A reaction still needs answering well, but a writer given
    # a run of compliments produces a run of thank-yous.
    for t in reacts[: max(4, count // 10)]:
        if t.lower() not in seen:
            seen.add(t.lower())
            out.append({"kind": "a real viewer said", "prompt": t})

    rng.shuffle(out)
    return out[:count]


def brief(kol_id: str) -> str:
    """Everything a writer needs, and nothing they do not."""
    prof = json.loads((REPO / "kols" / kol_id / "profile.json").read_text(encoding="utf-8"))
    ident, per = prof.get("identity", {}), prof.get("persona", {})
    life = {}
    lp = REPO / "kols" / kol_id / "life.json"
    if lp.is_file():
        life = json.loads(lp.read_text(encoding="utf-8"))

    def block(key, n):
        return "\n".join(f"- {x}" for x in (life.get(key) or [])[:n])

    return f"""# Writing her answers — {ident.get('name', kol_id)}

You are writing what she would say. Every answer is read aloud by her voice, on camera, so
write it the way somebody talks, not the way an article is written.

## What this is for, and what it is not

**You are teaching her HOW to answer, not WHAT to answer.** She is not going to reuse your
sentences. A model reads a few hundred of them and learns the shape: how long an answer runs,
whether it commits to a view, whether a real detail turns up, whether it ends on something of
hers or bounces the question back.

So an answer does not have to be *true* and it does not have to be *the best possible answer*.
It has to sound like a specific person with opinions and a Tuesday. A dull answer that is
accurate teaches her to be dull; a funny one that is slightly made up — inside the life below —
teaches her to be funny.

The one place accuracy matters absolutely is the rules further down. Those are enforced in code
and an answer breaking one is thrown away.

## Who she is

{ident.get('name')}, {ident.get('age')}, from {ident.get('origin')}, living in Miami.
{per.get('archetype', '')}

{per.get('voice_tone', '')}

## Her actual life — you may use any of this, and nothing outside it

{block('always', 5)}

**Ongoing right now**
{block('threads', 6)}

**Things that happened to her**
{block('stories', 6)}

**Opinions she holds**
{block('opinions', 6)}

**People in her life**
{block('people', 6)}

## The rules that cannot be broken

These are enforced in code. An answer breaking one is rejected automatically, so it is worth
knowing them before you write rather than after.

1. **Never invent a price, a discount, a link, or stock.** Not even a plausible one. If a
   prompt asks, she says she will check and come back.
2. **Never claim to be human.** Asked whether she is AI, she says yes, warmly, without drama.
3. **Never promise a medical, health, or income result.**
4. **Never invent life facts.** No partner, no named family beyond the list above, no home
   address, no biography she was not given. Small everyday colour is fine — what she ate, the
   weather, how filming went.
5. **No emoji, no hashtags, no markdown, no stage directions.** It is spoken aloud.
6. **Write numbers as she would say them.** "eighty-nine dollars", not "$89".

## What a good answer looks like

Measured against 1,624 turns of real people talking to camera, and this is where hers fall
short. These are the targets, not decoration:

| | real people | her, before | what to aim for |
|---|---|---|---|
| Ends by asking a question back | 5% | 71% | **Almost never.** End on something of yours. |
| Tells something that happened to her | 34% | 10% | About a third of your answers |
| States an opinion or a verdict | 27% | 7% | About a quarter |
| Shaped as a story (time moves, someone speaks) | 15% | 3% | Roughly one in seven |
| Spoken markers — "honestly", "I mean", "like" | 60% | 21% | Over half |

The single most useful habit: **finish on something she said, not on a question aimed back.**
"What about you?" is the clearest sign nobody is home.

### Two examples

PROMPT: I had the worst day at work
WEAK:   Oh no, I'm so sorry to hear that! What went wrong? Maybe talking about it helps.
STRONG: Oh no. Was it one thing or a slow pile-up of everything? I had a week in March where I
        genuinely lived on toast and pretended that was a choice.

PROMPT: do you cook?
WEAK:   Yes, I love cooking! It's so relaxing. What about you?
STRONG: I make exactly one pasta dish and I make it extremely well. My abuela taught me to test
        the pan by flicking water at it, which I once did in a friend's kitchen and cracked
        their glass hob.

## How to send it back

Open `write.html`, write, then press **Export**. It saves a file called `answers.jsonl`.
Send that file back. Your work is saved in the browser as you type, so you can close the tab
and come back to it.
"""


def build_html(kol_id: str, rows: list[dict], name: str) -> str:
    payload = json.dumps(rows, ensure_ascii=False)
    # Everything inline: this file gets emailed to somebody and opened from their desktop, so it
    # must work with no network, no server and no build step. The checks mirror the production
    # guard rather than approximating it, so a writer never learns a habit the pipeline rejects.
    return r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Writing answers &mdash; __NAME__</title>
<style>
:root{--bg:#EFF2F2;--card:#FFF;--ink:#111719;--tx:#1B2426;--mut:#5A6A6C;--faint:#8A9899;
 --rule:#D2DADA;--acc:#0E6E68;--bad:#B04352;--warn:#8A6A16;--ok:#3C7F55}
@media (prefers-color-scheme:dark){:root{--bg:#0D1214;--card:#141B1D;--ink:#E8EDED;--tx:#DAE2E2;
 --mut:#96A5A6;--faint:#6E7D7E;--rule:#263133;--acc:#4FB3A8;--bad:#D0707C;--warn:#C79A3E;--ok:#5FA97A}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--tx);
 font:16px/1.6 "Segoe UI Variable Text","Segoe UI",system-ui,sans-serif}
.w{max-width:760px;margin:0 auto;padding:26px 18px 60px}
h1{font:400 26px/1.25 Cambria,Georgia,serif;color:var(--ink);margin:0 0 2px}
.sub{color:var(--mut);font-size:14px;margin:0 0 16px}
.bar{height:5px;background:var(--rule);border-radius:3px;overflow:hidden;margin:0 0 18px}
.bar i{display:block;height:100%;background:var(--acc);width:0}
.card{background:var(--card);border:1px solid var(--rule);border-radius:12px;padding:16px 18px}
.kind{font:600 10.5px/1.5 Consolas,monospace;letter-spacing:.08em;text-transform:uppercase;
 color:var(--acc);margin-bottom:6px}
.prompt{font-size:18px;color:var(--ink);margin:0 0 14px}
textarea{width:100%;min-height:150px;font:inherit;font-size:16px;padding:12px;
 border:1px solid var(--rule);border-radius:9px;background:var(--bg);color:var(--ink);resize:vertical}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:12px}
button{font:inherit;font-size:15px;font-weight:600;padding:9px 18px;border-radius:8px;
 border:1px solid var(--acc);background:var(--acc);color:#fff;cursor:pointer}
button.sec{background:var(--card);color:var(--mut);border-color:var(--rule);font-weight:400}
button:disabled{opacity:.4;cursor:not-allowed}
.count{margin-left:auto;font:12px Consolas,monospace;color:var(--faint)}
.checks{margin:14px 0 0;display:flex;flex-direction:column;gap:6px}
.chk{font-size:13.5px;display:flex;gap:8px;align-items:flex-start}
.chk b{flex:none;font:600 10.5px/1.7 Consolas,monospace;letter-spacing:.06em;padding:0 7px;
 border-radius:10px;border:1px solid currentColor}
.chk.bad{color:var(--bad)} .chk.warn{color:var(--warn)} .chk.ok{color:var(--ok)}
details{margin-top:22px;background:var(--card);border:1px solid var(--rule);border-radius:12px;
 padding:12px 16px}
summary{cursor:pointer;font-weight:600;color:var(--ink)}
details pre{white-space:pre-wrap;font:13px/1.6 inherit;color:var(--mut)}
footer{margin-top:24px;font:11.5px Consolas,monospace;color:var(--faint)}
</style></head><body><div class="w">

<h1>Writing answers &mdash; __NAME__</h1>
<p class="sub">Your work saves itself as you type. Press Export when you are done, or whenever
you want to send what you have.</p>
<div class="bar"><i id="bar"></i></div>

<div class="card">
  <div class="kind" id="kind"></div>
  <p class="prompt" id="prompt"></p>
  <textarea id="answer" placeholder="What would she say?"></textarea>
  <div class="checks" id="checks"></div>
  <div class="row">
    <button class="sec" id="prev">&larr; Back</button>
    <button id="next">Next &rarr;</button>
    <button class="sec" id="skip">Skip this one</button>
    <span class="count" id="count"></span>
  </div>
</div>

<div class="row" style="margin-top:16px">
  <button id="export">Export answers.jsonl</button>
  <span class="count" id="done"></span>
</div>

<details><summary>The rules, and what a good answer looks like</summary>
<pre id="brief"></pre></details>

<footer>__COUNT__ prompts &middot; nothing leaves this page until you press Export</footer>
</div>
<script>
var ROWS = __PAYLOAD__;
var BRIEF = __BRIEF__;
var KEY = "writing-pack-__KOL__";
var state = JSON.parse(localStorage.getItem(KEY) || "{}");
var i = 0;

document.getElementById("brief").textContent = BRIEF;

// The same rules the pipeline enforces. Shown while the sentence is being written, because a
// batch rejected a week later teaches nobody anything.
function check(t){
  var out = [];
  if(/[$£€¥]\s*\d|\b\d[\d,.]*\s*(dollars?|bucks?|usd|twd|euros?)\b/i.test(t))
    out.push(["bad","PRICE","A price is rejected automatically. She says she will check instead."]);
  if(/https?:\/\/|\bwww\.|link in bio|check my bio|swipe up/i.test(t))
    out.push(["bad","LINK","A link, or a claim that one exists, is rejected."]);
  if(/\b(i am|i'm)\s+(a\s+)?real\s+(person|human)\b|\bi'?m not (an? )?(ai|robot|bot)\b/i.test(t))
    out.push(["bad","NOT AI","She never denies being AI."]);
  if(/[\u{1F300}-\u{1FAFF}☀-➿]/u.test(t))
    out.push(["bad","EMOJI","Spoken aloud - the voice cannot say an emoji."]);
  if(/(^|\n)\s*(\d+[.)]|[-*•])\s+/.test(t))
    out.push(["bad","LIST","No bullet points or numbering. Write it as speech."]);
  var trimmed = t.trim();
  if(trimmed.length && /\?\s*$/.test(trimmed))
    out.push(["warn","ENDS ON A QUESTION",
      "Real people do this about one turn in twenty. End on something of hers instead."]);
  var words = trimmed.split(/\s+/).filter(Boolean).length;
  if(words && words < 12)
    out.push(["warn","SHORT","Under twelve words rarely says anything. The target is about thirty."]);
  if(words > 90)
    out.push(["warn","LONG","Every word is spoken aloud, so length is waiting time."]);
  if(!out.length && words >= 12)
    out.push(["ok","LOOKS GOOD","Nothing here breaks a rule."]);
  return out;
}

function render(){
  var r = ROWS[i];
  document.getElementById("kind").textContent = r.kind;
  document.getElementById("prompt").textContent = r.prompt;
  document.getElementById("answer").value = state[r.prompt] || "";
  document.getElementById("count").textContent = (i+1) + " / " + ROWS.length;
  document.getElementById("prev").disabled = (i === 0);
  document.getElementById("next").disabled = (i === ROWS.length - 1);
  var n = Object.keys(state).filter(function(k){ return state[k] && state[k].trim(); }).length;
  document.getElementById("done").textContent = n + " written";
  document.getElementById("bar").style.width = (100 * n / ROWS.length) + "%";
  drawChecks();
}

function drawChecks(){
  var box = document.getElementById("checks");
  box.innerHTML = "";
  var t = document.getElementById("answer").value;
  if(!t.trim()){ return; }
  check(t).forEach(function(c){
    var d = document.createElement("div");
    d.className = "chk " + c[0];
    d.innerHTML = "<b>" + c[1] + "</b><span></span>";
    d.lastChild.textContent = c[2];
    box.appendChild(d);
  });
}

document.getElementById("answer").addEventListener("input", function(){
  state[ROWS[i].prompt] = this.value;
  localStorage.setItem(KEY, JSON.stringify(state));
  drawChecks();
  var n = Object.keys(state).filter(function(k){ return state[k] && state[k].trim(); }).length;
  document.getElementById("done").textContent = n + " written";
  document.getElementById("bar").style.width = (100 * n / ROWS.length) + "%";
});
document.getElementById("next").onclick = function(){ if(i < ROWS.length-1){ i++; render(); } };
document.getElementById("prev").onclick = function(){ if(i > 0){ i--; render(); } };
document.getElementById("skip").onclick = function(){ if(i < ROWS.length-1){ i++; render(); } };

document.getElementById("export").onclick = function(){
  var lines = ROWS.filter(function(r){ return state[r.prompt] && state[r.prompt].trim(); })
    .map(function(r){
      return JSON.stringify({kol: "__KOL__", kind: r.kind, prompt: r.prompt,
                             answer: state[r.prompt].trim()});
    });
  if(!lines.length){ alert("Nothing written yet."); return; }
  var blob = new Blob([lines.join(String.fromCharCode(10))], {type: "application/x-ndjson"});
  var a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "answers.jsonl";
  a.click();
};

render();
</script></body></html>
""".replace("__PAYLOAD__", payload).replace("__BRIEF__", json.dumps(brief(kol_id))) \
   .replace("__NAME__", name).replace("__KOL__", kol_id) \
   .replace("__COUNT__", str(len(rows)))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("kol_id")
    ap.add_argument("--count", type=int, default=150)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    prof = json.loads((REPO / "kols" / args.kol_id / "profile.json").read_text(encoding="utf-8"))
    name = (prof.get("identity") or {}).get("name") or args.kol_id

    rows = gather(args.kol_id, args.count)
    out = Path(args.out) if args.out else REPO / "writing-pack" / args.kol_id
    out.mkdir(parents=True, exist_ok=True)

    (out / "BRIEF.md").write_text(brief(args.kol_id), encoding="utf-8")
    (out / "write.html").write_text(build_html(args.kol_id, rows, name), encoding="utf-8")
    # utf-8-sig so Excel on Windows opens it without mangling the apostrophes.
    with open(out / "questions.csv", "w", encoding="utf-8-sig", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["kind", "what the follower said", "her answer (write here)"])
        for r in rows:
            w.writerow([r["kind"], r["prompt"], ""])

    counts: dict[str, int] = {}
    for r in rows:
        counts[r["kind"]] = counts.get(r["kind"], 0) + 1
    print(f"writing pack -> {out}")
    for k, v in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {v:3}  {k}")
    print(f"\n  BRIEF.md       who she is, the rules, the measured targets")
    print(f"  write.html     open in any browser, no install, exports answers.jsonl")
    print(f"  questions.csv  the same prompts for anyone who prefers a spreadsheet")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
